version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:3000'
    volumes:
      - ./src:/usr/app/src
      - ./.env:/usr/app/.env
    depends_on:
      - db
  adminer:
    image: adminer
    env_file:
      - .env
    ports:
      - '${ADMINER_PORT}:8080'
    depends_on:
      - db
  db:
    image: postgres:10.3
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'